# Nginx
#
# VERSION               0.0.1

FROM      ubuntu
MAINTAINER Guilhem Lettron "guilhem@lettron.fr"

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list

# make sure the package repository is up to date
RUN apt-get update

RUN apt-get install -y redis-server
